//
//  RoutesInterfaces.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RoutesWireframeInterface: WireframeInterface {
}

protocol RoutesViewInterface: ViewInterface {
}

protocol RoutesPresenterInterface: PresenterInterface {
}

protocol RoutesFormatterInterface: FormatterInterface {
}

protocol RoutesInteractorInterface: InteractorInterface {
}
