//
//  RoutesInterfaces.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RoutesWireframeInterface: WireframeInterface {
    func navigateBack()
    func navigateToMap(recom: Recom)
}

protocol RoutesViewInterface: ViewInterface {
    func showLoading()
    func hideLoading()
    func showRecoms(recoms: [Recom])
}

protocol RoutesPresenterInterface: PresenterInterface {
    func backButtonTap()
    func viewDidLoad()
    func didSelectRecom(recom: Recom)
}

protocol RoutesFormatterInterface: FormatterInterface {
}

protocol RoutesInteractorInterface: InteractorInterface {
    func fetchRecommendation(completion: (([Recom])->Void)?)
}
