//
//  RoutesInterfaces.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RoutesWireframeInterface: WireframeInterface {
    func navigateBack()
}

protocol RoutesViewInterface: ViewInterface {
    func showLoading()
    func hideLoading()
}

protocol RoutesPresenterInterface: PresenterInterface {
    func backButtonTap()
    func viewDidLoad()
}

protocol RoutesFormatterInterface: FormatterInterface {
}

protocol RoutesInteractorInterface: InteractorInterface {
    func fetchRecommendation(completion: (([Int])->Void)?)
}
