//
//  RoutesInteractor.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RoutesInteractor {
}

// MARK: - Extensions -

extension RoutesInteractor: RoutesInteractorInterface {
    func fetchRecommendation(completion: (([Int]) -> Void)?) {
        Timer.scheduledTimer(withTimeInterval: 1, repeats: false, block: { _ in
            completion?([1,2,3])
        })
    }
}
