//
//  RoutesViewController.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RoutesViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RoutesPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension RoutesViewController: RoutesViewInterface {
}
