//
//  RoutesPresenter.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RoutesPresenter {
    
    // MARK: - Private properties -

    private unowned let view: RoutesViewInterface
    private let formatter: RoutesFormatterInterface
    private let interactor: RoutesInteractorInterface
    private let wireframe: RoutesWireframeInterface

    // MARK: - Lifecycle -

    init(view: RoutesViewInterface, formatter: RoutesFormatterInterface, interactor: RoutesInteractorInterface, wireframe: RoutesWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RoutesPresenter: RoutesPresenterInterface {
    func backButtonTap() {
        wireframe.navigateBack()
    }
    
    func viewDidLoad() {
        interactor.fetchRecommendation { [weak self] recoms in
            self?.view.hideLoading()
            self?.view.showRecoms(recoms: recoms)
        }
        view.showLoading()
    }
    
    func didSelectRecom(recom: Recom) {
        wireframe.navigateToMap(recom: recom)
    }
}
