//
//  RoutesInteractor.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RoutesInteractor {
}

// MARK: - Extensions -

extension RoutesInteractor: RoutesInteractorInterface {
}
