//
//  RoutesFormatter.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RoutesFormatter {
}

// MARK: - Extensions -

extension RoutesFormatter: RoutesFormatterInterface {
}
