//
//  RoutesInteractor.swift
//  Jampang
//
//  Created by Fitsyu  on 28/07/24.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RoutesInteractor {
}

// MARK: - Extensions -

extension RoutesInteractor: RoutesInteractorInterface {
    func fetchRecommendation(completion: (([Recom]) -> Void)?) {
        let task = URLSession.shared.dataTask(with: URLRequest(url: URL(string: "https://kmbmicro.co.id/angelhack/vendor/2/recommendation")!)) { data, _, _ in
            
            do {
                let decoder = JSONDecoder()
                decoder.keyDecodingStrategy = .convertFromSnakeCase
                let object = try decoder.decode([Recom].self, from: data!)
                
                DispatchQueue.main.async {
                    completion?(object)
                }
                
            } catch {
                print(error)
            }
        }
        
        task.resume()
    }
}
